version: "3.8"
services:
  mysql:
    container_name: mysql_local
    image: mysql:8.0.30
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d  # my.cnf 파일을 마운트
      - ./db/initdb.d:/docker-entrypoint-initdb.d # 초기 SQL 파일을 마운트
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=passlocal123
      - MYSQL_ROOT_PASSWORD=passlocal123
      - TZ=Asia/Seoul
    command:
      --character-set-server=utf8mb4 
      --collation-server=utf8mb4_general_ci
      --init_connect='SET NAMES utf8mb4'
      --init_connect='SET character_set_results=utf8mb4'
